language: node_js
node_js:
  - "8.4.0"
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
script:
  - yarn lint
  - yarn build
